version: "1"
services:
  - type: web
    name: SR.BSM
    runtime: node
    repo: https://github.com/MOTEB1989/BSM
    region: virginia
    buildCommand: npm ci
    startCommand: npm start
    preDeployCommand: npm install
    envVars:
      - key: NODE_ENV
        sync: false
      - key: RENDER_DEPLOY_HOOK
        sync: false
      - key: PERPLEXITY_KEY
        sync: false
      - key: KIMI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_BSM_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: ADMIN_TOKEN
        sync: false
    domains:
      - www.corehub.nexus
      - corehub.nexus
      - lexprim.com
      - www.lexprim.com
    autoDeployTrigger: "off"
